### ISSUE TITLE
Github Action workflow: bad function name

### ISSUE THREAD

**Issue by DanielLopez-nbcuni** [docksal/bitbucket-pipelines-agent#88]
When using `docksal/ci-agent:latest` OR `docksal/ci-agent:edge-php` and using the github workflow example. 

```
name: Docksal sandbox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docksal/ci-agent:edge-php
    env:
      CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
      DOCKSAL_HOST_IP: ${{ secrets.DOCKSAL_HOST_IP }}
      DOCKSAL_HOST_SSH_KEY: ${{ secrets.DOCKSAL_HOST_SSH_KEY }}
      GITHUB_TOKEN: ${{ github.token }}
      REMOTE_CODEBASE_METHOD: git
    steps:
      - name: Build sandbox
        run: |
          source build-env
          sandbox-init
```

Got the following error;
`/__w/_temp/088f377d-c351-4fb2-a72b-53e3f1b60aa4.sh: /usr/local/bin/build-env: line 32: syntax error: bad function name
Error: Process completed with exit code 2.`
